### ISSUE TITLE
Fix: fcm token 로그인 구현

### ISSUE THREAD

**Issue by pkl0912** [Kusitms-POPTATO-DEV/Poptato_Server_V2#45]
## 📌 목적 / 이슈 내용

> 내용
fcm 로그인
## 📝 상세 내용

- 내용

## ✔ 체크 리스트
- [ ] 내용

## 💡 비고

- (참고 사항 및 레퍼런스)
- 내용

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added FCM token handling in the AuthService login method. This includes saving or updating the FCM token for the user, and sending a welcome notification for new users.

You can review changes in this commit: https://github.com/lkilu6456546/Kusitms-POPTATO-DEV-Poptato_Server_V2-45/commit/5d91a1475443de9d15c0db404ebeae9f9fc1e0a0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
